# Configuration for yetAnotherClipCutter
# Place this file in your /script-opts/ directory

# Output directory for clips (MUST have double backslash or trailing slash on windows like C:\\Clips\\)
target_path=

# Path to ffmpeg binary (can be just "ffmpeg" if in your PATH)
ffmpeg_bin=ffmpeg

# Keybindings
time_start_key=;
time_end_key='
mode_switch_key=\

# --- Custom Modes ---
# Define custom clipping modes below.
#
# Each mode requires exactly TWO lines (blank lines and comments starting with # are ignored).
# Line 1: The Mode Name (displayed in OSD)
# Line 2: The FFmpeg arguments followed by the output extension (e.g. .mp4)
# 
# Special placeholders you can use in -vf:
# {subtitles} - Modes using this perform a two-pass subtitle extraction that uses a temp .ass file in order to burn in subs
# {crop} - Automatically gets replaced by mpv's active crop filter (e.g., `crop=W:H:X:Y,`)
#
# Examples below:

MP4 reencode
-c:v libx264 -vf scale=-1:720,format=yuv420p -ac 2 -y .mp4

MP4 subtitle burn
-c:v libx264 -vf {subtitles},format=yuv420p -ac 2 -y .mp4

GIF resized
-vf scale=-1:432:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse -y .gif

GIF cropped
-vf {crop}split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse -y .gif

MP4 copy
-c copy -y .mp4
